/**
 * Agent-Powered Seed Script
 *
 * Replaces hardcoded seed templates with data generated by the actual agent pipeline.
 * Each "vibe" (raw user input) flows through: subject line → decision makers → message → moderation → DB save.
 *
 * Usage:
 *   tsx scripts/seed-with-agents.ts
 *
 * Required env vars:
 *   GEMINI_API_KEY   - Gemini API for subject line, decision makers, message generation, quality moderation
 *
 * Optional env vars:
 *   GROQ_API_KEY     - Llama Guard safety moderation (skipped if absent)
 *   EXA_API_KEY      - Exa source discovery (falls back to Google grounding if absent)
 *   DATABASE_URL     - Database connection (defaults to local)
 */

import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import type { InputJsonValue } from '@prisma/client/runtime/library';

// Agent pipeline imports — called directly, no HTTP server needed
// tsx resolves $lib via scripts/tsconfig.json paths; SvelteKit virtual modules
// ($app/environment, $env/dynamic/private) are shimmed by scripts/shims/
import { generateSubjectLine } from '$lib/core/agents/agents/subject-line';
import { resolveDecisionMakers } from '$lib/core/agents/agents/decision-maker';
import { generateMessage } from '$lib/core/agents/agents/message-writer';
import { moderateTemplate } from '$lib/core/server/moderation/index';
import type { DecisionMaker, GeoScope } from '$lib/core/agents/types';
import type { ResolveContext } from '$lib/core/agents/providers/types';

const db = new PrismaClient();

// ============================================================================
// VIBES — Raw user inputs that drive the pipeline
// ============================================================================

const VIBES = [
	{
		vibe: "Climate disaster costs are $178 billion but we still give $7.4 billion in fossil fuel subsidies. The math doesn't work.",
		fallbackCategory: 'Environment'
	},
	{
		vibe: "35% of SF offices are empty but only 1 building is converting to housing. 61,000 potential units sitting vacant.",
		fallbackCategory: 'Housing'
	},
	{
		vibe: "Median home is $400k, median income is $75k. Takes 11 years to save a down payment. Housing math is broken.",
		fallbackCategory: 'Housing'
	},
	{
		vibe: "Kids spend 7 hours online daily, 72 million data points collected per child per year, and our privacy laws haven't changed since 1998.",
		fallbackCategory: 'Digital Rights'
	},
	{
		vibe: "Uber made $9.8 billion profit but their drivers average $318/week. Record profits, poverty wages.",
		fallbackCategory: 'Labor Rights'
	},
	{
		vibe: "Insulin costs $4 to produce but sells for $315. That's a 100x markup on a drug people need to survive.",
		fallbackCategory: 'Healthcare'
	}
];

// ============================================================================
// SEED USERS — reused from seed-database.ts
// ============================================================================

const seedUserData = [
	{
		id: 'user-demo-1',
		email: 'demo@communi.email',
		name: 'ETHDenver Demo',
		is_verified: true,
		verification_method: 'didit',
		verified_at: new Date(),
		document_type: 'passport',
		authority_level: 4,
		birth_year: 1990,
		trust_score: 100,
		reputation_tier: 'verified',
		role: 'Civic Technologist',
		organization: 'ETHDenver',
		location: 'Denver, CO',
		profile_completed_at: new Date(),
		profile_visibility: 'public',
		templates_contributed: 0,
		template_adoption_rate: 0.0,
		peer_endorsements: 0,
		active_months: 0
	},
	{
		id: 'user-demo-2',
		email: 'test@communi.email',
		name: 'Test User',
		is_verified: false,
		trust_score: 0,
		reputation_tier: 'novice',
		templates_contributed: 0,
		template_adoption_rate: 0.0,
		peer_endorsements: 0,
		active_months: 0
	}
];

// ============================================================================
// HELPERS
// ============================================================================

function generateSlug(title: string): string {
	return title
		.toLowerCase()
		.replace(/[^a-z0-9\s-]/g, '')
		.replace(/\s+/g, '-')
		.replace(/-+/g, '-')
		.replace(/^-|-$/g, '')
		.substring(0, 50);
}

function sleep(ms: number): Promise<void> {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

function inferDeliveryMethod(
	targetType: string | null | undefined,
	geoScope?: GeoScope
): string {
	// Federal / congressional → CWC
	if (targetType === 'government') {
		if (!geoScope || geoScope.type === 'nationwide' || geoScope.type === 'international') {
			return 'cwc';
		}
		// Subnational government → email (city/state officials)
		if (geoScope.type === 'subnational' && geoScope.locality) {
			return 'email';
		}
		return 'cwc';
	}
	// Corporate / institutional → email
	return 'email';
}

function buildRecipientConfig(
	decisionMakers: DecisionMaker[],
	deliveryMethod: string
): Record<string, unknown> {
	if (deliveryMethod === 'cwc') {
		return {
			reach: 'district-based',
			cwcRouting: true,
			chambers: ['house', 'senate']
		};
	}

	return {
		reach: 'location-specific',
		decisionMakers: decisionMakers.map((dm) => ({
			name: dm.name,
			shortName: dm.name.split(' ').pop(),
			role: dm.title,
			organization: dm.organization,
			email: dm.email
		})),
		emails: decisionMakers.map((dm) => dm.email).filter(Boolean)
	};
}

// ============================================================================
// TEARDOWN — same dependency order as seed-database.ts
// ============================================================================

async function teardownDatabase() {
	console.log('Starting complete database teardown...');

	const deletions = [
		{ name: 'analytics_event', fn: () => db.analytics_event.deleteMany({}) },
		{ name: 'analytics_session', fn: () => db.analytics_session.deleteMany({}) },
		{ name: 'analytics_experiment', fn: () => db.analytics_experiment.deleteMany({}) },
		{ name: 'reward_calculation', fn: () => db.rewardCalculation.deleteMany({}) },
		{ name: 'template_jurisdiction', fn: () => db.templateJurisdiction.deleteMany({}) },
		{ name: 'template_scope', fn: () => db.templateScope.deleteMany({}) },
		{ name: 'template_analytics', fn: () => db.template_analytics.deleteMany({}) },
		{ name: 'template_campaign', fn: () => db.template_campaign.deleteMany({}) },
		{ name: 'template_morphism', fn: () => db.template_morphism.deleteMany({}) },
		{ name: 'template_adaptation', fn: () => db.template_adaptation.deleteMany({}) },
		{ name: 'ai_suggestions', fn: () => db.ai_suggestions.deleteMany({}) },
		{ name: 'message', fn: () => db.message.deleteMany({}) },
		{ name: 'delivery_log', fn: () => db.deliveryLog.deleteMany({}) },
		{ name: 'submission', fn: () => db.submission.deleteMany({}) },
		{ name: 'user_representatives', fn: () => db.user_representatives.deleteMany({}) },
		{ name: 'user_writing_style', fn: () => db.user_writing_style.deleteMany({}) },
		{ name: 'user_email', fn: () => db.userEmail.deleteMany({}) },
		{ name: 'encrypted_delivery_data', fn: () => db.encryptedDeliveryData.deleteMany({}) },
		{ name: 'session', fn: () => db.session.deleteMany({}) },
		{ name: 'account', fn: () => db.account.deleteMany({}) },
		{ name: 'agent_dissent', fn: () => db.agentDissent.deleteMany({}) },
		{ name: 'agent_performance', fn: () => db.agentPerformance.deleteMany({}) },
		{ name: 'legislative_body', fn: () => db.legislative_body.deleteMany({}) },
		{ name: 'legislative_channel', fn: () => db.legislative_channel.deleteMany({}) },
		{ name: 'shadow_atlas_tree', fn: () => db.shadowAtlasTree.deleteMany({}) },
		{ name: 'template', fn: () => db.template.deleteMany({}) },
		{ name: 'representative', fn: () => db.representative.deleteMany({}) },
		{ name: 'user', fn: () => db.user.deleteMany({}) }
	];

	for (const { name, fn } of deletions) {
		try {
			const result = await fn();
			if (result.count > 0) {
				console.log(`  Deleted ${result.count} ${name} records`);
			}
		} catch {
			console.log(`  Skipped ${name} (table may not exist)`);
		}
	}

	console.log('Database teardown complete\n');
}

// ============================================================================
// MAIN PIPELINE
// ============================================================================

async function processVibe(
	vibe: string,
	fallbackCategory: string,
	userId: string,
	index: number
): Promise<boolean> {
	console.log(`\n${'='.repeat(60)}`);
	console.log(`VIBE ${index + 1}/6: "${vibe.substring(0, 60)}..."`);
	console.log('='.repeat(60));

	// ── Step 1: Subject Line Generation ──────────────────────────
	console.log('\n[1/5] Generating subject line...');
	let subjectResult;
	try {
		subjectResult = await generateSubjectLine({ description: vibe });
	} catch (err) {
		console.error('  FAILED:', err instanceof Error ? err.message : err);
		return false;
	}

	const subjectData = subjectResult.data;

	// If needs clarification, retry with a more direct prompt
	if (subjectData.needs_clarification || !subjectData.subject_line) {
		console.log('  Agent asked for clarification, retrying with direct prompt...');
		try {
			subjectResult = await generateSubjectLine({
				description: `Write a congressional advocacy template about: ${vibe}. This is a clear policy issue, generate the subject line directly.`,
				previousInteractionId: subjectResult.interactionId
			});
		} catch (err) {
			console.error('  FAILED on retry:', err instanceof Error ? err.message : err);
			return false;
		}
	}

	const title = subjectResult.data.subject_line || vibe.substring(0, 60);
	const coreMessage = subjectResult.data.core_message || vibe;
	const topics = subjectResult.data.topics || [fallbackCategory];
	const urlSlug = subjectResult.data.url_slug || generateSlug(title);
	const voiceSample = subjectResult.data.voice_sample || '';
	const inferredContext = subjectResult.data.inferred_context;

	console.log(`  Title: "${title}"`);
	console.log(`  Core: "${coreMessage.substring(0, 80)}..."`);
	console.log(`  Topics: [${topics.join(', ')}]`);
	console.log(`  Slug: ${urlSlug}`);

	// ── Step 2: Decision Maker Resolution ────────────────────────
	console.log('\n[2/5] Resolving decision makers...');

	// Build context from inferred data
	const targetType = inferredContext?.detected_target_type || 'government';
	const resolveContext: ResolveContext = {
		targetType,
		subjectLine: title,
		coreMessage,
		topics,
		voiceSample
	};

	// Add geographic scope if detected
	if (inferredContext?.detected_location) {
		const scope = inferredContext.detected_scope;
		if (scope === 'local' || scope === 'state') {
			resolveContext.geographicScope = {
				state: inferredContext.detected_location,
				displayName: inferredContext.detected_location
			};
		}
	}

	let dmResult;
	try {
		dmResult = await resolveDecisionMakers(resolveContext, (segment) => {
			// Log streaming events for visibility
			if (segment.type === 'identity-found') {
				console.log(`  Found: ${segment.content}`);
			} else if (segment.type === 'candidate-resolved') {
				console.log(`  Resolved: ${segment.content}`);
			}
		});
	} catch (err) {
		console.error('  FAILED:', err instanceof Error ? err.message : err);
		return false;
	}

	const decisionMakers: DecisionMaker[] = dmResult.decisionMakers.map((dm) => ({
		name: dm.name,
		title: dm.title || '',
		organization: dm.organization || '',
		email: dm.email || '',
		reasoning: dm.reasoning || '',
		sourceUrl: dm.sourceUrl || '',
		emailSource: dm.emailSource || '',
		emailGrounded: dm.emailGrounded ?? false,
		confidence: dm.confidence ?? 0.5,
		contactChannel: dm.contactChannel || 'email'
	}));

	console.log(`  Found ${decisionMakers.length} decision maker(s)`);
	for (const dm of decisionMakers) {
		console.log(`    - ${dm.name} (${dm.title}, ${dm.organization}) <${dm.email}>`);
	}

	// ── Step 3: Message Generation ───────────────────────────────
	console.log('\n[3/5] Generating message (two-phase: sources + writing)...');

	let messageResult;
	try {
		messageResult = await generateMessage({
			subjectLine: title,
			coreMessage,
			topics,
			decisionMakers,
			voiceSample,
			rawInput: vibe,
			onPhase: (phase, msg) => {
				console.log(`  [${phase}] ${msg}`);
			}
		});
	} catch (err) {
		console.error('  FAILED:', err instanceof Error ? err.message : err);
		return false;
	}

	console.log(`  Message length: ${messageResult.message.length} chars`);
	console.log(`  Sources: ${messageResult.sources.length}`);
	for (const src of messageResult.sources) {
		console.log(`    [${src.num}] ${src.title} (${src.type})`);
	}

	// ── Step 4: Moderation ───────────────────────────────────────
	console.log('\n[4/5] Running moderation pipeline...');

	let moderationResult;
	try {
		moderationResult = await moderateTemplate({
			title,
			message_body: messageResult.message,
			category: fallbackCategory
		});
	} catch (err) {
		console.error('  Moderation error (non-fatal):', err instanceof Error ? err.message : err);
		// Non-fatal — save as draft
		moderationResult = { approved: false, summary: 'moderation_error' };
	}

	const approved = moderationResult.approved;
	console.log(`  Result: ${approved ? 'APPROVED' : 'REJECTED'} (${moderationResult.summary})`);

	// ── Step 5: Database Save ────────────────────────────────────
	console.log('\n[5/5] Saving to database...');

	const geoScope = messageResult.geographic_scope;
	const deliveryMethod = inferDeliveryMethod(targetType, geoScope);
	const recipientConfig = buildRecipientConfig(decisionMakers, deliveryMethod);

	const slug = urlSlug || generateSlug(title);

	// Ensure slug uniqueness
	const existingSlug = await db.template.findFirst({ where: { slug } });
	const finalSlug = existingSlug ? `${slug}-${Date.now()}` : slug;

	const template = await db.template.create({
		data: {
			title,
			slug: finalSlug,
			description: coreMessage,
			message_body: messageResult.message,
			sources: (messageResult.sources || []) as unknown as InputJsonValue,
			research_log: (messageResult.research_log || []) as unknown as InputJsonValue,
			category: fallbackCategory,
			topics: topics as unknown as InputJsonValue,
			type: 'advocacy',
			deliveryMethod,
			preview: messageResult.message.substring(0, 200),
			delivery_config: (deliveryMethod === 'cwc'
				? { timing: 'immediate', followUp: true, cwcEnabled: true }
				: { timing: 'immediate', followUp: false, cwcEnabled: false }) as InputJsonValue,
			cwc_config: (deliveryMethod === 'cwc'
				? { topic: topics[0] || fallbackCategory, urgency: 'high', policy_area: fallbackCategory }
				: {}) as InputJsonValue,
			recipient_config: recipientConfig as InputJsonValue,
			metrics: {
				sent: 0,
				opened: 0,
				clicked: 0,
				responded: 0,
				districts_covered: 0,
				total_districts: 435,
				district_coverage_percent: 0
			} as InputJsonValue,
			status: approved ? 'published' : 'draft',
			is_public: approved,
			verification_status: approved ? 'approved' : 'pending',
			consensus_approved: approved,
			country_code: 'US',
			reputation_applied: false,
			verified_sends: 0,
			unique_districts: 0,
			reputation_delta: 0,
			user: { connect: { id: userId } }
		}
	});

	console.log(`  Created template: ${template.id} (/${finalSlug})`);

	// Create TemplateScope if geographic scope exists
	if (geoScope && geoScope.type !== 'international') {
		try {
			const scopeLevel =
				geoScope.type === 'nationwide'
					? 'country'
					: 'subdivision' in geoScope && geoScope.locality
						? 'locality'
						: 'region';

			await db.templateScope.create({
				data: {
					template_id: template.id,
					country_code: ('country' in geoScope ? geoScope.country : 'US') || 'US',
					region_code: 'subdivision' in geoScope ? (geoScope.subdivision ?? null) : null,
					locality_code: 'locality' in geoScope ? (geoScope.locality ?? null) : null,
					display_text: ('displayName' in geoScope ? geoScope.displayName : null) || geoScope.type,
					scope_level: scopeLevel,
					confidence: 1.0,
					extraction_method: 'gemini_inline'
				}
			});
			console.log(`  Created TemplateScope (${scopeLevel})`);
		} catch (err) {
			console.error('  TemplateScope creation failed (non-fatal):', err instanceof Error ? err.message : err);
		}
	}

	// Create TemplateJurisdiction based on inferred context
	try {
		const jurisdictionType =
			inferredContext?.detected_scope === 'local'
				? 'city'
				: inferredContext?.detected_scope === 'state'
					? 'state'
					: 'federal';

		await db.templateJurisdiction.create({
			data: {
				template_id: template.id,
				jurisdiction_type: jurisdictionType,
				state_code: geoScope && 'subdivision' in geoScope ? (geoScope.subdivision ?? null) : null
			}
		});
		console.log(`  Created TemplateJurisdiction (${jurisdictionType})`);
	} catch (err) {
		console.error('  TemplateJurisdiction creation failed (non-fatal):', err instanceof Error ? err.message : err);
	}

	console.log(`  DONE: "${title}" saved as ${approved ? 'published' : 'draft'}`);
	return true;
}

// ============================================================================
// MAIN
// ============================================================================

async function main() {
	console.log('\n' + '='.repeat(60));
	console.log('AGENT-POWERED SEED');
	console.log('Processing 6 vibes through the real agent pipeline');
	console.log('='.repeat(60));

	// Check required env vars
	if (!process.env.GEMINI_API_KEY) {
		console.error('\nFATAL: GEMINI_API_KEY is required.');
		console.error('Set it in .env or pass it directly:');
		console.error('  GEMINI_API_KEY=your-key tsx scripts/seed-with-agents.ts');
		process.exit(1);
	}

	if (!process.env.GROQ_API_KEY) {
		console.log('\nNote: GROQ_API_KEY not set. Llama Guard safety moderation will be skipped.');
	}

	try {
		// Step 1: Teardown
		await teardownDatabase();

		// Step 2: Create seed users
		console.log('Seeding users...');
		const createdUsers = [];
		for (const userData of seedUserData) {
			const user = await db.user.create({ data: userData });
			createdUsers.push(user);
			console.log(`  Created: "${userData.name}" (${userData.email})`);
		}

		// Step 3: Process each vibe through the full pipeline
		let successCount = 0;
		let failCount = 0;

		const vibeLimit = parseInt(process.env.VIBE_LIMIT || '0') || VIBES.length;
	for (let i = 0; i < Math.min(vibeLimit, VIBES.length); i++) {
			const { vibe, fallbackCategory } = VIBES[i];
			const userId = createdUsers[i % createdUsers.length].id;

			try {
				const success = await processVibe(vibe, fallbackCategory, userId, i);
				if (success) {
					successCount++;
				} else {
					failCount++;
				}
			} catch (err) {
				console.error(`\nVibe ${i + 1} crashed:`, err);
				failCount++;
			}

			// Rate limit delay between vibes (skip after last one)
			if (i < VIBES.length - 1) {
				console.log('\n  Waiting 5s for rate limits...');
				await sleep(5000);
			}
		}

		// Step 4: Summary
		const counts = {
			users: await db.user.count(),
			templates: await db.template.count(),
			published: await db.template.count({ where: { status: 'published' } }),
			drafts: await db.template.count({ where: { status: 'draft' } })
		};

		console.log('\n' + '='.repeat(60));
		console.log('SEED COMPLETE');
		console.log('='.repeat(60));
		console.log(`Users:      ${counts.users}`);
		console.log(`Templates:  ${counts.templates} (${counts.published} published, ${counts.drafts} drafts)`);
		console.log(`Pipeline:   ${successCount} succeeded, ${failCount} failed`);
		console.log('='.repeat(60));
	} catch (error) {
		console.error('\nFATAL:', error);
		process.exit(1);
	} finally {
		await db.$disconnect();
	}
}

main();
